#!/bin/bash

# Author: Bruno Guimarães
# Description: Setup environment for ci
# Version: 1.0
# Last Updated: 20/02/2025

INFO='\033[0;34m[BRLK INFO]'

echo -e "$INFO - Generating local.properties file..."
echo $LOCAL_PROPERTIES | base64 --decode > local.properties
echo -e "$INFO - Word Count: $(cat local.properties | wc -w)"
echo -e "$INFO - Bytes Count: $(cat local.properties | wc -c)"

echo -e "$INFO - Generating gradle.properties file..."
echo $GRADLE_PROPERTIES | base64 --decode > gradle.properties
echo -e "$INFO - Word Count: $(cat gradle.properties | wc -w)"
echo -e "$INFO - Bytes Count: $(cat gradle.properties | wc -c)"

echo -e  "$INFO - Generating google-services.json file..."
echo $GOOGLE_SERVICES | base64 --decode > app/google-services.json
echo -e "$INFO - Word Count: $(cat app/google-services.json | wc -w)"
echo -e "$INFO - Bytes Count: $(cat app/google-services.json | wc -c)"

echo -e "$INFO - Generating dev-services-account.json file..."
echo $DEV_SERVICE_ACCOUNT | base64 --decode > app/dev-service-account.json
echo -e "$INFO - Word Count: $(cat app/dev-service-account.json | wc -w)"
echo -e "$INFO - Bytes Count: $(cat app/dev-service-account.json | wc -c)"

echo -e "$INFO - Generating release-key.jks file..."
echo $RELEASE_KEY | base64 --decode > app/release-key.jks
echo -e "$INFO - Word Count: $(cat app/release-key.jks | wc -w)"
echo -e "$INFO - Bytes Count: $(cat app/release-key.jks | wc -c)"

# Exit with success status
exit 0
