version: 2.1

executors:
  docker-android:
    docker:
      - image: cimg/android:2025.02.1

orbs:
  android: circleci/android@3.1.0

jobs:
  # Done
  lint:
    executor: docker-android
    steps:
      - checkout
      - run:
          name: Setup environment
          command: chmod +x setup_environment && ./setup_environment
      - restore_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: Lint Release
          command: ./gradlew lintRelease
      - store_artifacts:
          path: app/build/reports

  # Done
  unit-tests:
    executor: docker-android
    steps:
      - checkout
      - run:
          name: Setup environment
          command: chmod +x setup_environment && ./setup_environment
      - restore_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: Run Unit Tests
          command: ./gradlew testReleaseUnitTest
      - store_test_results:
          path: app/build/test-results
      - save_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
          paths:
            - ~/.gradle/caches

  # In progress
  # - Test persist to workspace
  build:
    executor: docker-android
    steps:
      - checkout
      - run:
          name: Setup environment
          command: chmod +x setup_environment && ./setup_environment
      - restore_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: Lint Release Only
          command: ./gradlew lintRelease
      - run:
          name: Build Release AAB
          command: ./gradlew bundleRelease
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease
      - save_cache:
          key: cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
          paths:
            - ~/.gradle/caches
      - persist_to_workspace:
          root: app/build
          paths:
            - outputs/apk/release
            - outputs/bundle/release
            - outputs/bundle/*.aab

  # In progress
  # - Retrieve build from workspace
  deploy:
    executor: docker-android
    steps:
      - checkout
      - attach_workspace:
          at: app
      - run:
          name: Debug
          command: apt-get install tree && tree
      - run:
          name: Setup environment
          command: chmod +x setup_environment && ./setup_environment
      - run:
          name: Upload to Google Play
          command: ./gradlew publishReleaseBundle
      - store_artifacts:
          path: workspace

# In progress
# - Logic to trigger full-pipeline in tag pushes
workflows:
  full-pipeline:
    jobs:
      - lint
      - unit-tests
      - android/run_ui_tests:
          executor:
            name: android/android_machine
            resource_class: large
            tag: default

          pre_test_command: 'chmod +x setup_environment && ./setup_environment'

          pre_emulator_wait_steps:
            - run:
                name: Setupbrlk
                command: |
                  chmod +x setup_environment
                  ./setup_environment

          pre_run_tests_steps:
            - run:
                name: Setupbrlk
                command: |
                  chmod +x setup_environment
                  ./setup_environment

          matrix:
            parameters:
              system_image:
                - system-images;android-30;default;x86_64
                - system-images;android-29;default;x86_64
          name: ui-tests-<<matrix.system_image>>
      - build:
          requires:
            - unit-tests
            - lint
            - android/run_ui_tests
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/  # Deploy only if there's a tag in format vX.Y.Z
