name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      ADMOB_APP_ID: ${{ secrets.ADMOB_APP_ID }}
      INTERSTITIAL_AD_UNIT_ID: ${{ secrets.INTERSTITIAL_AD_UNIT_ID }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      DEV_SERVICE_ACCOUNT: ${{ secrets.DEV_SERVICE_ACCOUNT }}
      RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
      ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS }}
      ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD }}
      ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_STORE_FILE }}
      ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          chmod +x setup_environment
          ./setup_environment

      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest

      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: app/build/reports/tests
