name: Manually deploy to Amazon App Store

on:
  workflow_dispatch:

jobs:
  deploy-amazon-appstore:
    runs-on: ubuntu-latest
    needs: build-apk
    steps:
      - uses: dawidd6/action-download-artifact@v8
        with:
          workflow: build-and-test.yml
          name: release-artifacts

      - name: Get APK name
        id: get_apk_name
        run: |
          APK_PATH=$(ls outputs/apk/release/*.apk | head -1)
          echo "APK_NAME=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload to Amazon App Store
        uses: AmeyaJain-25/amazon-appstore-app-upload@v1.0.0
        with:
          client_id: ${{secrets.AMAZON_APPSTORE_CLIENT_ID}}
          client_secret: ${{secrets.AMAZON_APPSTORE_CLIENT_SECRET}}
          app_id: ${{ secrets.AMAZON_APPSTORE_APP_ID }}
          apk_release_file: ${{ steps.get_apk_name.outputs.APK_NAME }}
